name = "ghostwriter"
license = "MIT"
licenselink = "https://github.com/k0pernicus/ghostwriter/blob/master/LICENSE.md"
description = "A fork of the Ghost blogging platform fork, for Hugo."
homepage = "https://github.com/k0pernicus/ghostwriter"
tags = ["website", "blog", "technical", "personal"]
features = ["website", "blog", "technical", "personal"]
min_version = 0.15

[author]
		name = "Carette Antonin"
		homepage = "https://github.com/k0pernicus"

[original]
    name = "Juraj Bubniak"
    homepage = "https://github.com/jbub"
